var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => NetworkSyntaxPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// languages/tokenizer.ts
function esc(s) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
function sticky(src) {
  return new RegExp(src, "y");
}
function alt(tokens) {
  const unique = [...new Set(tokens)].sort((a, b) => b.length - a.length);
  return "(?:" + unique.map(escLit).join("|") + ")";
}
function escLit(s) {
  return s.replace(/[.*+?^${}()|[\]\\/\-]/g, "\\$&");
}
function tokenize(source, rules) {
  let out = "";
  let pos = 0;
  const len = source.length;
  while (pos < len) {
    let matched = false;
    for (const rule of rules) {
      rule.pattern.lastIndex = pos;
      const m = rule.pattern.exec(source);
      if (m && m.index === pos) {
        out += `<span class="token ${rule.type}">${esc(m[0])}</span>`;
        pos += m[0].length;
        matched = true;
        break;
      }
    }
    if (!matched) {
      out += esc(source[pos]);
      pos++;
    }
  }
  return out;
}

// languages/routeros.ts
var PATHS = [
  "/ip firewall filter",
  "/ip firewall nat",
  "/ip firewall mangle",
  "/ip firewall raw",
  "/ip firewall address-list",
  "/ip firewall connection",
  "/ip firewall service-port",
  "/ip neighbor discovery-settings",
  "/ip dhcp-server network",
  "/ip dhcp-server lease",
  "/ip dhcp-server config",
  "/ip dhcp-server",
  "/ip dhcp-client",
  "/ip dhcp-relay",
  "/ip ipsec installed-sa",
  "/ip ipsec active-peers",
  "/ip ipsec statistics",
  "/ip ipsec peer",
  "/ip ipsec profile",
  "/ip ipsec proposal",
  "/ip ipsec policy",
  "/ip ipsec identity",
  "/ip ipsec",
  "/ip traffic-flow target",
  "/ip traffic-flow",
  "/ip accounting snapshot",
  "/ip accounting web-access",
  "/ip accounting",
  "/ip upnp interfaces",
  "/ip upnp",
  "/ip address",
  "/ip route",
  "/ip neighbor",
  "/ip dns static",
  "/ip dns cache",
  "/ip dns",
  "/ip pool",
  "/ip service",
  "/ip ssh",
  "/ip smb",
  "/ip proxy",
  "/ip arp",
  "/ip cloud advanced",
  "/ip cloud",
  "/ip packing",
  "/ip vrf",
  "/ip",
  "/ipv6 firewall filter",
  "/ipv6 firewall nat",
  "/ipv6 firewall mangle",
  "/ipv6 firewall raw",
  "/ipv6 firewall address-list",
  "/ipv6 firewall",
  "/ipv6 dhcp-server binding",
  "/ipv6 dhcp-server",
  "/ipv6 dhcp-client",
  "/ipv6 nd prefix",
  "/ipv6 nd",
  "/ipv6 address",
  "/ipv6 route",
  "/ipv6 neighbor",
  "/ipv6 pool",
  "/ipv6 settings",
  "/ipv6",
  "/interface ethernet switch port",
  "/interface ethernet switch rule",
  "/interface ethernet switch host",
  "/interface ethernet switch",
  "/interface wireless registration-table",
  "/interface wireless security-profiles",
  "/interface wireless access-list",
  "/interface wireless connect-list",
  "/interface wireless nstreme-dual",
  "/interface wireless nstreme",
  "/interface wireless snooper",
  "/interface wireless align",
  "/interface wireless",
  "/interface bridge settings",
  "/interface bridge filter",
  "/interface bridge calea",
  "/interface bridge port",
  "/interface bridge vlan",
  "/interface bridge mdb",
  "/interface bridge nat",
  "/interface bridge",
  "/interface pppoe-server server",
  "/interface pppoe-client",
  "/interface pppoe-server",
  "/interface pptp-server server",
  "/interface pptp-client",
  "/interface pptp-server",
  "/interface l2tp-server server",
  "/interface l2tp-client",
  "/interface l2tp-server",
  "/interface sstp-server server",
  "/interface sstp-client",
  "/interface sstp-server",
  "/interface ovpn-server server",
  "/interface ovpn-client",
  "/interface ovpn-server",
  "/interface wireguard peers",
  "/interface wireguard",
  "/interface list member",
  "/interface list",
  "/interface bonding",
  "/interface vlan",
  "/interface eoipv6",
  "/interface eoip",
  "/interface gre6",
  "/interface gre",
  "/interface ipip",
  "/interface ipipv6",
  "/interface 6to4",
  "/interface lte apn",
  "/interface lte settings",
  "/interface lte",
  "/interface w60g station",
  "/interface w60g",
  "/interface vrrp",
  "/interface vpls",
  "/interface mpls",
  "/interface traffic-eng",
  "/interface ethernet",
  "/interface dot11",
  "/interface wds",
  "/interface",
  "/routing ospf interface-template",
  "/routing ospf area range",
  "/routing ospf static-neighbor",
  "/routing ospf instance",
  "/routing ospf neighbor",
  "/routing ospf area",
  "/routing ospf lsa",
  "/routing ospf",
  "/routing bgp advertisement",
  "/routing bgp connection",
  "/routing bgp template",
  "/routing bgp network",
  "/routing bgp peer",
  "/routing bgp vpls",
  "/routing bgp",
  "/routing rip interface-template",
  "/routing rip instance",
  "/routing rip neighbor",
  "/routing rip network",
  "/routing rip",
  "/routing filter community-list",
  "/routing filter aspath-list",
  "/routing filter num-list",
  "/routing filter rule",
  "/routing filter",
  "/routing igmp-proxy interface",
  "/routing igmp-proxy",
  "/routing pimsm interface-template",
  "/routing pimsm instance",
  "/routing pimsm",
  "/routing table",
  "/routing mme",
  "/routing",
  "/mpls traffic-eng interface",
  "/mpls traffic-eng tunnel",
  "/mpls traffic-eng",
  "/mpls ldp interface",
  "/mpls ldp neighbor",
  "/mpls ldp",
  "/mpls forwarding-table",
  "/mpls local-label",
  "/mpls remote-bindings",
  "/mpls",
  "/queue simple",
  "/queue tree",
  "/queue type",
  "/queue interface",
  "/queue",
  "/system routerboard usb-power-reset",
  "/system routerboard settings",
  "/system routerboard mode-button",
  "/system routerboard upgrade",
  "/system routerboard",
  "/system logging action",
  "/system logging",
  "/system ntp client servers",
  "/system ntp client",
  "/system ntp server",
  "/system ntp",
  "/system package update",
  "/system package",
  "/system resource cpu",
  "/system resource irq",
  "/system resource pci",
  "/system resource usb",
  "/system resource",
  "/system leds settings",
  "/system leds",
  "/system default-configuration",
  "/system certificate",
  "/system scheduler",
  "/system script",
  "/system watchdog",
  "/system clock",
  "/system console",
  "/system health",
  "/system history",
  "/system identity",
  "/system upgrade",
  "/system",
  "/tool mac-server mac-winbox",
  "/tool mac-server ping",
  "/tool mac-server",
  "/tool graphing interface",
  "/tool graphing queue",
  "/tool graphing resource",
  "/tool graphing",
  "/tool sniffer packet",
  "/tool sniffer protocol",
  "/tool sniffer statistics",
  "/tool sniffer",
  "/tool bandwidth-test",
  "/tool flood-ping",
  "/tool netwatch",
  "/tool traffic-generator",
  "/tool traceroute",
  "/tool romon port",
  "/tool romon",
  "/tool profile",
  "/tool e-mail",
  "/tool fetch",
  "/tool torch",
  "/tool ping",
  "/tool sniff",
  "/tool telnet",
  "/tool tftp",
  "/tool sms",
  "/tool wol",
  "/tool",
  "/caps-man actual-interface-configuration",
  "/caps-man registration-table",
  "/caps-man manager interface",
  "/caps-man configuration",
  "/caps-man provisioning",
  "/caps-man access-list",
  "/caps-man datapath",
  "/caps-man security",
  "/caps-man channel",
  "/caps-man manager",
  "/caps-man",
  "/capssman",
  "/certificate settings",
  "/certificate scep-server",
  "/certificate",
  "/user ssh-keys private",
  "/user ssh-keys",
  "/user settings",
  "/user group",
  "/user aaa",
  "/user",
  "/ppp profile",
  "/ppp secret",
  "/ppp active",
  "/ppp aaa",
  "/ppp",
  "/radius incoming",
  "/radius",
  "/snmp community",
  "/snmp",
  "/port firmware",
  "/port remote-access",
  "/port",
  "/container config",
  "/container mounts",
  "/container envs",
  "/container",
  "/zerotier controller member",
  "/zerotier controller",
  "/zerotier interface",
  "/zerotier",
  "/partitions",
  "/disk",
  "/file",
  "/log",
  "/console"
];
var COMMANDS = [
  "reset-configuration",
  "reset-counters",
  "reset-password",
  "without-paging",
  "quick-print",
  "count-only",
  "deauthorize",
  "disconnect",
  "deactivate",
  "uninstall",
  "authorize",
  "partition",
  "passthrough",
  "shutdown",
  "poweroff",
  "download",
  "generate",
  "activate",
  "disable",
  "comment",
  "monitor",
  "resolve",
  "release",
  "upgrade",
  "install",
  "restore",
  "execute",
  "profile",
  "convert",
  "destroy",
  "connect",
  "receive",
  "forward",
  "compact",
  "replace",
  "untrack",
  "recover",
  "remove",
  "enable",
  "export",
  "import",
  "submit",
  "update",
  "reboot",
  "backup",
  "cancel",
  "upload",
  "revoke",
  "expire",
  "create",
  "accept",
  "reject",
  "unmark",
  "detail",
  "append",
  "unbind",
  "unlock",
  "reauth",
  "insert",
  "format",
  "print",
  "reset",
  "check",
  "flush",
  "renew",
  "start",
  "clear",
  "sniff",
  "torch",
  "fetch",
  "issue",
  "leave",
  "brief",
  "terse",
  "unset",
  "paste",
  "track",
  "eject",
  "edit",
  "find",
  "move",
  "save",
  "load",
  "stop",
  "push",
  "pull",
  "test",
  "ping",
  "scan",
  "sign",
  "join",
  "sync",
  "send",
  "drop",
  "mark",
  "copy",
  "bind",
  "lock",
  "kill",
  "add",
  "set",
  "get",
  "run",
  "log",
  "raw"
];
var SCRIPT_COLON = [
  ":environment",
  ":currentline",
  ":timestamp",
  ":continue",
  ":terminal",
  ":foreach",
  ":nothing",
  ":warning",
  ":execute",
  ":resolve",
  ":toarray",
  ":jobname",
  ":onerror",
  ":finally",
  ":return",
  ":global",
  ":tobool",
  ":typeof",
  ":while",
  ":break",
  ":local",
  ":error",
  ":debug",
  ":delay",
  ":parse",
  ":retry",
  ":toip6",
  ":tonum",
  ":tostr",
  ":catch",
  ":else",
  ":info",
  ":beep",
  ":time",
  ":toid",
  ":toip",
  ":pick",
  ":find",
  ":for",
  ":set",
  ":put",
  ":log",
  ":len",
  ":rnd",
  ":abs",
  ":try",
  ":if",
  ":do"
];
var SCRIPT_PLAIN = ["while", "false", "from", "step", "true", "nil", "in", "to", "do"];
var PROPERTIES = [
  "verify-server-address-from-certificate",
  "loop-protect-send-interval",
  "loop-protect-disable-time",
  "per-connection-classifier",
  "verify-server-certificate",
  "sfp-shutdown-temperature",
  "default-client-tx-limit",
  "adaptive-noise-immunity",
  "unknown-multicast-flood",
  "redistribute-other-ospf",
  "authentication-protocol",
  "authentication-password",
  "nv2-noise-floor-offset",
  "default-authentication",
  "default-route-distance",
  "redistribute-connected",
  "bgp-large-communities",
  "noise-floor-threshold",
  "nv2-quality-threshold",
  "unknown-unicast-flood",
  "connection-nat-state",
  "address-list-timeout",
  "bgp-atomic-aggregate",
  "persistent-keepalive",
  "bridge-port-priority",
  "loop-protect-status",
  "new-connection-mark",
  "bgp-ext-communities",
  "secondary-frequency",
  "default-ap-tx-limit",
  "multicast-buffering",
  "insert-queue-before",
  "pcq-burst-threshold",
  "ntp-server-dns-name",
  "disk-lines-per-file",
  "memory-stop-on-full",
  "retransmit-interval",
  "redistribute-static",
  "confederation-peers",
  "encryption-protocol",
  "encryption-password",
  "out-interface-list",
  "nv2-downlink-ratio",
  "wds-default-bridge",
  "default-forwarding",
  "disconnect-timeout",
  "on-fail-retry-time",
  "use-vj-compression",
  "vlink-transit-area",
  "in-interface-list",
  "wireless-protocol",
  "nv2-preshared-key",
  "frames-per-window",
  "supported-rates-b",
  "max-station-count",
  "ingress-filtering",
  "keepalive-timeout",
  "add-default-route",
  "red-min-threshold",
  "red-max-threshold",
  "disk-stop-on-full",
  "vlink-neighbor-id",
  "stub-default-cost",
  "nexthop-propagate",
  "default-originate",
  "remove-private-as",
  "export-passphrase",
  "import-passphrase",
  "auto-negotiation",
  "src-address-list",
  "dst-address-list",
  "connection-state",
  "connection-limit",
  "new-routing-mark",
  "ospf-metric-type",
  "security-profile",
  "tdma-period-size",
  "multicast-helper",
  "keepalive-frames",
  "multicast-router",
  "endpoint-address",
  "always-broadcast",
  "bridge-path-cost",
  "redistribute-bgp",
  "redistribute-rip",
  "out-filter-chain",
  "address-families",
  "digest-algorithm",
  "rx-flow-control",
  "tx-flow-control",
  "src-mac-address",
  "layer7-protocol",
  "connection-mark",
  "connection-type",
  "connection-rate",
  "new-packet-mark",
  "new-mangle-mark",
  "burst-threshold",
  "hw-offload-l2tp",
  "bgp-communities",
  "nv2-cell-radius",
  "nv2-sync-secret",
  "wds-ignore-ssid",
  "allow-sharedkey",
  "max-message-age",
  "broadcast-flood",
  "allowed-address",
  "delay-threshold",
  "pcq-total-limit",
  "session-timeout",
  "incoming-filter",
  "outgoing-filter",
  "use-compression",
  "syslog-severity",
  "syslog-facility",
  "disk-file-count",
  "in-filter-chain",
  "revocation-date",
  "trap-generators",
  "cable-settings",
  "bgp-local-pref",
  "bgp-aggregator",
  "rate-selection",
  "vlan-filtering",
  "remote-address",
  "dial-on-demand",
  "ca-certificate",
  "boot-file-name",
  "sfq-perturbate",
  "red-avg-packet",
  "pcq-classifier",
  "pcq-burst-rate",
  "pcq-burst-time",
  "use-encryption",
  "change-tcp-mss",
  "bridge-horizon",
  "disk-file-name",
  "hello-interval",
  "transmit-delay",
  "metric-default",
  "nssa-translate",
  "keepalive-time",
  "nexthop-choice",
  "invalid-before",
  "trap-community",
  "out-interface",
  "routing-table",
  "check-gateway",
  "channel-width",
  "tx-power-mode",
  "compress-data",
  "preamble-mode",
  "running-check",
  "protocol-mode",
  "forward-delay",
  "igmp-snooping",
  "dhcp-snooping",
  "local-address",
  "preshared-key",
  "endpoint-port",
  "clamp-tcp-mss",
  "bootp-support",
  "authoritative",
  "dead-interval",
  "update-source",
  "route-reflect",
  "confederation",
  "serial-number",
  "invalid-after",
  "loop-protect",
  "in-interface",
  "icmp-options",
  "routing-mark",
  "to-addresses",
  "address-list",
  "target-scope",
  "antenna-gain",
  "antenna-mode",
  "installation",
  "nv2-security",
  "fast-forward",
  "igmp-version",
  "auto-isolate",
  "service-name",
  "use-peer-dns",
  "use-peer-ntp",
  "ipsec-secret",
  "parent-queue",
  "lease-script",
  "idle-timeout",
  "ntp-min-poll",
  "ntp-max-poll",
  "memory-lines",
  "network-type",
  "redistribute",
  "no-summaries",
  "organization",
  "trap-version",
  "write-access",
  "mac-address",
  "arp-timeout",
  "src-address",
  "dst-address",
  "packet-size",
  "jump-target",
  "burst-limit",
  "packet-mark",
  "reject-with",
  "bgp-prepend",
  "ospf-metric",
  "nv2-quality",
  "bridge-mode",
  "ageing-time",
  "mld-version",
  "frame-types",
  "remote-port",
  "compression",
  "certificate",
  "tls-version",
  "private-key",
  "wins-server",
  "next-server",
  "pfifo-limit",
  "bfifo-limit",
  "metric-type",
  "as-override",
  "allow-as-in",
  "tcp-md5-key",
  "tcp-md5-sas",
  "common-name",
  "ca-crl-host",
  "fingerprint",
  "trap-target",
  "ip-address",
  "combo-mode",
  "log-prefix",
  "burst-time",
  "bgp-weight",
  "rip-metric",
  "local-port",
  "public-key",
  "remote-mac",
  "lease-time",
  "dns-server",
  "ntp-server",
  "use-radius",
  "option-set",
  "rate-limit",
  "ntp-client",
  "start-date",
  "start-time",
  "categories",
  "bsd-syslog",
  "domain-tag",
  "local-role",
  "cluster-id",
  "days-valid",
  "layer2mtu",
  "advertise",
  "bandwidth",
  "tcp-flags",
  "frequency",
  "scan-list",
  "vlan-mode",
  "hide-ssid",
  "tunnel-id",
  "local-mac",
  "client-id",
  "host-name",
  "direction",
  "max-limit",
  "sfq-allot",
  "red-limit",
  "red-burst",
  "pcq-limit",
  "router-id",
  "area-type",
  "domain-id",
  "remote-as",
  "hold-time",
  "peer-mode",
  "key-usage",
  "issued-to",
  "issued-by",
  "community",
  "addresses",
  "interface",
  "disabled",
  "protocol",
  "src-port",
  "dst-port",
  "new-dscp",
  "to-ports",
  "priority",
  "fragment",
  "tls-host",
  "distance",
  "pref-src",
  "ospf-tag",
  "wps-mode",
  "tx-power",
  "wds-mode",
  "rate-set",
  "dfs-mode",
  "untagged",
  "password",
  "limit-at",
  "pcq-rate",
  "only-one",
  "use-mpls",
  "use-upnp",
  "identity",
  "timezone",
  "ntp-mode",
  "interval",
  "on-event",
  "instance",
  "multihop",
  "key-size",
  "locality",
  "ocsp-url",
  "location",
  "security",
  "comment",
  "address",
  "network",
  "gateway",
  "tcp-mss",
  "content",
  "new-ttl",
  "new-tos",
  "hotspot",
  "bgp-med",
  "rip-tag",
  "country",
  "nstreme",
  "vlan-id",
  "horizon",
  "profile",
  "ac-name",
  "max-mtu",
  "max-mru",
  "add-arp",
  "netmask",
  "on-down",
  "servers",
  "enabled",
  "subject",
  "area-id",
  "passive",
  "connect",
  "trusted",
  "request",
  "crl-url",
  "contact",
  "duplex",
  "master",
  "action",
  "random",
  "tagged",
  "bridge",
  "secret",
  "cipher",
  "server",
  "domain",
  "option",
  "target",
  "parent",
  "policy",
  "source",
  "topics",
  "prefix",
  "remote",
  "listen",
  "output",
  "filter",
  "speed",
  "slave",
  "chain",
  "limit",
  "every",
  "scope",
  "learn",
  "relay",
  "queue",
  "on-up",
  "owner",
  "level",
  "email",
  "input",
  "state",
  "name",
  "type",
  "dscp",
  "port",
  "flow",
  "ssid",
  "mode",
  "band",
  "pvid",
  "edge",
  "user",
  "mrru",
  "auth",
  "kind",
  "from",
  "body",
  "area",
  "cost",
  "unit",
  "sign",
  "akid",
  "skid",
  "mtu",
  "arp",
  "ttl",
  "tos",
  "log",
  "nth",
  "hw",
  "to",
  "as",
  "ca"
];
var VALUES = [
  "station-pseudobridge-clone",
  "add-src-to-address-list",
  "add-dst-to-address-list",
  "icmp-proto-unreachable",
  "icmp-host-unreachable",
  "icmp-port-unreachable",
  "icmp-admin-prohibited",
  "fasttrack-connection",
  "station-pseudobridge",
  "icmp-net-unreachable",
  "strip-ipv4-options",
  "nstreme-dual-slave",
  "transport-requires",
  "aggressively-drop",
  "aggressively-pass",
  "ethernet-default",
  "wireless-default",
  "mark-connection",
  "local-proxy-arp",
  "hotspot-default",
  "station-bridge",
  "alignment-only",
  "point-to-point",
  "ptp-unnumbered",
  "ptm-unnumbered",
  "ebgp-rs-client",
  "ibgp-rr-client",
  "default-small",
  "provider-edge",
  "customer-edge",
  "active-backup",
  "mark-routing",
  "camellia-128",
  "camellia-192",
  "camellia-256",
  "passthrough",
  "mark-packet",
  "change-dscp",
  "established",
  "station-wds",
  "balance-alb",
  "balance-tlb",
  "balance-xor",
  "change-mss",
  "change-ttl",
  "masquerade",
  "sniff-tzsp",
  "reply-only",
  "balance-rr",
  "untracked",
  "ipv6-icmp",
  "proxy-arp",
  "wireguard",
  "ap-bridge",
  "wds-slave",
  "broadcast",
  "transport",
  "tcp-reset",
  "clear-df",
  "redirect",
  "sniff-pc",
  "disabled",
  "backbone",
  "provider",
  "blowfish",
  "twofish",
  "802.3ad",
  "ebgp-rs",
  "ibgp-rr",
  "notrack",
  "src-nat",
  "dst-nat",
  "related",
  "invalid",
  "udplite",
  "enabled",
  "bonding",
  "station",
  "vpls-pe",
  "ec-p256",
  "ec-p384",
  "ec-p521",
  "aes-128",
  "aes-192",
  "aes-256",
  "netmap",
  "tarpit",
  "srcnat",
  "dstnat",
  "accept",
  "reject",
  "return",
  "discard",
  "tunnel",
  "false",
  "true",
  "drop",
  "jump",
  "same",
  "none",
  "yes",
  "no",
  "new",
  "all"
];
var PROTOCOLS = [
  "mac-telnet",
  "mac-winbox",
  "wireguard",
  "zerotier",
  "ospf-v3",
  "udplite",
  "api-ssl",
  "icmpv6",
  "ipsec",
  "pppoe",
  "https",
  "tr069",
  "romon",
  "ripng",
  "pimsm",
  "ospf",
  "igmp",
  "gre6",
  "ipip",
  "eoip",
  "6to4",
  "pptp",
  "l2tp",
  "sstp",
  "ovpn",
  "sctp",
  "dccp",
  "icmp",
  "ipv6",
  "vrrp",
  "rsvp",
  "mpls",
  "http",
  "snmp",
  "upnp",
  "bgp",
  "rip",
  "pim",
  "mme",
  "vpn",
  "gre",
  "tcp",
  "udp",
  "esp",
  "ldp",
  "ssh",
  "ftp",
  "api",
  "ah"
];
var RULES = [
  // comment
  { type: "comment", pattern: sticky(/#.*/) },
  // strings
  { type: "string", pattern: sticky(/"[^"\\]*(?:\\[\s\S][^"\\]*)*"|'[^'\\]*(?:\\[\s\S][^'\\]*)*'/) },
  // IPv6 before IPv4
  { type: "ipv6", pattern: sticky(/(?:[0-9a-fA-F]{1,4}:){2,7}[0-9a-fA-F:]*(?:\/\d+)?/) },
  // IPv4 + CIDR
  { type: "ipv4", pattern: sticky(/\b(?:(?:25[0-5]|2[0-4]\d|[01]?\d\d?)\.){3}(?:25[0-5]|2[0-4]\d|[01]?\d\d?)(?:\/(?:3[0-2]|[12]?\d))?\b/) },
  // MAC address
  { type: "mac-address", pattern: sticky(/[0-9A-Fa-f]{2}(?::[0-9A-Fa-f]{2}){5}|[0-9A-Fa-f]{2}(?:-[0-9A-Fa-f]{2}){5}/) },
  // Duration
  { type: "duration", pattern: sticky(/(?:\d+[wdhms])+/) },
  // Percentage
  { type: "percentage", pattern: sticky(/\d+(?:\.\d+)?%/) },
  // Hex
  { type: "hexadecimal", pattern: sticky(/0x[0-9A-Fa-f]+/) },
  // Variable
  { type: "variable", pattern: sticky(/\$(?:"[^"]*"|\w+)/) },
  // Paths — longest first, must be followed by whitespace/= or end
  { type: "path", pattern: sticky(new RegExp(alt(PATHS) + "(?=\\s|=|$)")) },
  // Script keywords with colon
  { type: "script-keyword", pattern: sticky(new RegExp(alt(SCRIPT_COLON) + "(?=\\s|\\(|$)")) },
  // Script plain keywords — only as whole words
  { type: "script-keyword", pattern: sticky(new RegExp("\\b(?:" + SCRIPT_PLAIN.join("|") + ")\\b")) },
  // property=value — match key=val together, emit property + = + value spans
  { type: "_prop_val", pattern: sticky(new RegExp(alt(PROPERTIES) + "=[^\\s]*")) },
  // standalone commands
  { type: "command", pattern: sticky(new RegExp("\\b" + alt(COMMANDS) + "\\b")) },
  // firewall chain names
  { type: "firewall", pattern: sticky(/\b(?:input|output|forward|srcnat|dstnat|prerouting|postrouting|broute)\b/) },
  // protocols
  { type: "protocol", pattern: sticky(new RegExp("\\b" + alt(PROTOCOLS) + "\\b")) },
  // number
  { type: "number", pattern: sticky(/\b\d+(?:\.\d+)?\b/) },
  // operator
  { type: "operator", pattern: sticky(/!=|>=|<=|&&|\|\||->|[=<>!~+\-*/&|^]/) },
  // punctuation
  { type: "punctuation", pattern: sticky(/[{}[\]();,]/) }
];
function highlightPropVal(raw) {
  const eq = raw.indexOf("=");
  if (eq === -1)
    return `<span class="token property">${esc(raw)}</span>`;
  const key = raw.slice(0, eq);
  const val = raw.slice(eq + 1);
  const propSpan = `<span class="token property">${esc(key)}</span>`;
  const opSpan = `<span class="token operator">=</span>`;
  const knownVal = VALUES.find((v) => v === val);
  const valSpan = knownVal ? `<span class="token value">${esc(val)}</span>` : `<span class="token value">${esc(val)}</span>`;
  return propSpan + opSpan + valSpan;
}
function highlightRouterOS(source) {
  let out = "";
  let pos = 0;
  const len = source.length;
  while (pos < len) {
    let matched = false;
    for (const rule of RULES) {
      rule.pattern.lastIndex = pos;
      const m = rule.pattern.exec(source);
      if (m && m.index === pos) {
        if (rule.type === "_prop_val") {
          out += highlightPropVal(m[0]);
        } else {
          out += `<span class="token ${rule.type}">${esc(m[0])}</span>`;
        }
        pos += m[0].length;
        matched = true;
        break;
      }
    }
    if (!matched) {
      out += esc(source[pos]);
      pos++;
    }
  }
  return out;
}

// languages/cisco-ios.ts
var COMMANDS2 = [
  "spanning-tree",
  "storm-control",
  "authentication",
  "channel-group",
  "channel-protocol",
  "switchport",
  "description",
  "negotiation",
  "flowcontrol",
  "configure",
  "interface",
  "route-map",
  "access-list",
  "class-map",
  "policy-map",
  "service-policy",
  "snmp-server",
  "tacacs-server",
  "radius-server",
  "username",
  "privilege",
  "hostname",
  "terminal",
  "router",
  "crypto",
  "logging",
  "banner",
  "service",
  "default",
  "reload",
  "shutdown",
  "write",
  "copy",
  "erase",
  "network",
  "redistribute",
  "passive-interface",
  "summary-address",
  "default-information",
  "aggregate-address",
  "address-family",
  "neighbor",
  "remote-as",
  "update-source",
  "next-hop-self",
  "route-reflector-client",
  "confederation",
  "maximum-paths",
  "send-community",
  "activate",
  "vtp",
  "ntp",
  "aaa",
  "end",
  "exit",
  "show",
  "ping",
  "traceroute",
  "debug",
  "undebug",
  "clear",
  "clock",
  "verify",
  "test",
  "telnet",
  "ssh",
  "more",
  "type",
  "dir",
  "delete",
  "rename",
  "mkdir",
  "rmdir",
  "format",
  "fsck",
  "no",
  "ip",
  "ipv6",
  "line",
  "boot",
  "vlan",
  "permit",
  "deny",
  "remark",
  "evaluate",
  "nat",
  "overload",
  "pool",
  "static",
  "standby",
  "vrrp",
  "glbp",
  "match",
  "set",
  "police",
  "shape",
  "priority",
  "bandwidth",
  "queue-limit",
  "random-detect",
  "fair-queue"
];
var KEYWORDS = [
  "GigabitEthernet",
  "TenGigabitEthernet",
  "HundredGigE",
  "FortyGigabitEthernet",
  "TwentyFiveGigabitEthernet",
  "TwentyFiveGigE",
  "FastEthernet",
  "Ethernet",
  "Management",
  "Loopback",
  "Cellular",
  "Serial",
  "Tunnel",
  "Vlan",
  "Port-channel",
  "BVI",
  "Dialer",
  "established",
  "fragments",
  "sequence",
  "extended",
  "standard",
  "named",
  "ospf",
  "eigrp",
  "bgp",
  "static",
  "connected",
  "isis",
  "lisp",
  "odr",
  "rip",
  "any",
  "host",
  "log",
  "in",
  "out"
];
var RULES2 = [
  { type: "comment", pattern: sticky(/!.*/) },
  { type: "string", pattern: sticky(/"[^"]*"/) },
  { type: "ipv4", pattern: sticky(/\b(?:(?:25[0-5]|2[0-4]\d|[01]?\d\d?)\.){3}(?:25[0-5]|2[0-4]\d|[01]?\d\d?)(?:\/\d+)?\b/) },
  { type: "mac-address", pattern: sticky(/[0-9A-Fa-f]{4}\.[0-9A-Fa-f]{4}\.[0-9A-Fa-f]{4}|[0-9A-Fa-f]{2}(?::[0-9A-Fa-f]{2}){5}/) },
  { type: "important", pattern: sticky(/\bno\b/) },
  { type: "important", pattern: sticky(/\b(?:permit|deny)\b/) },
  { type: "command", pattern: sticky(new RegExp("\\b" + alt(COMMANDS2) + "\\b")) },
  { type: "keyword", pattern: sticky(new RegExp("\\b" + alt(KEYWORDS) + "\\b")) },
  { type: "number", pattern: sticky(/\b\d+(?:\.\d+)?\b/) },
  { type: "operator", pattern: sticky(/[=<>!]/) },
  { type: "punctuation", pattern: sticky(/[{}[\]();,]/) }
];
function highlightCiscoIOS(source) {
  return tokenize(source, RULES2);
}

// languages/index.ts
var LANGUAGE_REGISTRY = [
  {
    id: "routeros",
    name: "MikroTik RouterOS",
    aliases: ["ros", "mikrotik"],
    highlight: highlightRouterOS
  },
  {
    id: "ios",
    name: "Cisco IOS",
    aliases: ["cisco", "cisco-ios", "ios-xe"],
    highlight: highlightCiscoIOS
  }
];

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  disabledLanguages: [],
  showLanguageBadge: true
};
var NetworkSyntaxSettingsTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Network Syntax Highlighter" });
    containerEl.createEl("p", {
      text: "Enable or disable syntax highlighting per language. Changes take effect after reloading the plugin or restarting Obsidian.",
      cls: "setting-item-description"
    });
    containerEl.createEl("h3", { text: "Languages" });
    for (const lang of LANGUAGE_REGISTRY) {
      new import_obsidian.Setting(containerEl).setName(lang.name).setDesc(
        `Code block tags: \`${[lang.id, ...lang.aliases].join("`, `")}\``
      ).addToggle((toggle) => {
        toggle.setValue(!this.plugin.settings.disabledLanguages.includes(lang.id)).onChange(async (value) => {
          const disabled = this.plugin.settings.disabledLanguages;
          if (value) {
            const idx = disabled.indexOf(lang.id);
            if (idx !== -1)
              disabled.splice(idx, 1);
          } else {
            if (!disabled.includes(lang.id))
              disabled.push(lang.id);
          }
          await this.plugin.saveSettings();
        });
      });
    }
    containerEl.createEl("h3", { text: "Display" });
    new import_obsidian.Setting(containerEl).setName("Show language badge").setDesc("Display a small label in the top-right corner of highlighted blocks.").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.showLanguageBadge).onChange(async (value) => {
        this.plugin.settings.showLanguageBadge = value;
        await this.plugin.saveSettings();
      });
    });
    containerEl.createEl("h3", { text: "About" });
    containerEl.createEl("p", {
      text: "Supported languages: " + LANGUAGE_REGISTRY.map((l) => l.name).join(", ") + "."
    });
    containerEl.createEl("p", {
      text: "To add a new language, add a file to languages/ and register it in languages/index.ts.",
      cls: "setting-item-description"
    });
  }
};

// src/main.ts
var NetworkSyntaxPlugin = class extends import_obsidian2.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new NetworkSyntaxSettingsTab(this.app, this));
    for (const lang of LANGUAGE_REGISTRY) {
      const ids = [lang.id, ...lang.aliases];
      for (const id of ids) {
        this.registerMarkdownCodeBlockProcessor(id, (source, el, _ctx) => {
          this.renderBlock(source, el, lang, id);
        });
      }
    }
    console.log("[NetworkSyntax] Loaded \u2014", LANGUAGE_REGISTRY.map((l) => l.id).join(", "));
  }
  renderBlock(source, el, lang, id) {
    el.empty();
    const wrap = el.createDiv({ cls: "network-syntax-block" });
    const pre = wrap.createEl("pre", { cls: `language-${id}` });
    const code = pre.createEl("code", { cls: `language-${id}` });
    code.innerHTML = lang.highlight(source);
    if (this.settings.showLanguageBadge) {
      wrap.createDiv({ cls: "network-syntax-badge", text: lang.name });
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
